### PR TITLE
1.2.0

### PR DESCRIPTION
**Pull request by puddi**
Some users wanted some more features for 1.2.0, so here we go.

List of changes: 

* Tabs no longer have a defined maximum width. Instead, whenever the list of tabs is too long, there'll be handlers on the left and right to go between the tabs.

screen shot 2015-10-05 at 1 50 49 pm

* Clicking on a tab will scroll the tabs bar to that tab.

* When adding elements to a tab, the current tab will stay open after editor refresh, instead of going back to the first one.

* Changed 3D to Material

@tjsnyder @M-Porter @jennieab

### CODE REVIEW

**Comment by M-Porter** [comment]
@puddi Do you have a link to a live usage?

**Comment by puddi** [comment]
@M-Porter - http://welcometotheawakeningzonewevegotufn.weebly.com/

there's a bug where it doesn't select the first tab on load (which i'll fix), but the scrolling should work.

**Comment by M-Porter** [comment]
There is also a bug with the left border of the first tab that should be ironed out.

screen shot 2015-10-05 at 2 02 29 pm

**Comment by mattdeclaire** [comment]
This is what I see.

scrollbar

**Comment by M-Porter** [comment]
@mattdeclaire i noticed to and i told @puddi about it. We have a fix so that the scrollbar doesn't show.

**Comment by M-Porter** [comment]
(didn't mean to click close)

**Comment by puddi** [comment]
updated demo with the new changes can be found at the same link: http://welcometotheawakeningzonewevegotufn.weebly.com/

**Comment by mattdeclaire** [comment]
I would expect clicking on the arrow to simply scroll the bar, rather than actually navigating the tabs.  That would allow me to go straight from the first tab to the last tab without a bunch of content changes.

**Comment by M-Porter** [comment]
I felt the other way and though it felt weird that clicking the arrows did not switch tabs.

If we go with just scrolling like you suggest, I do feel that the tabs should scroll by 1 tab with each click.

**Comment by mattdeclaire** [comment]
I feel like it should approximate the behavior of a browser scrollbar.

#engineers-designing - We should probably get some qualified advice.

**Comment by M-Porter** [comment]
Agreed.

**Comment by jacalulu** [comment]
Just chatted with Lin (Design team) about the best UI/UX for this. 
1. The arrows should appear only on hover, and only when necessary (i.e. don't show the < arrow if #1 tab is already showing). 
2. Clicking the arrow should move the top row of tabs left/right, but should not change the active tab

@puddi let me know if this makes sense, happy to chat in person and explain the notes above.

**Comment by puddi** [comment]
@jacalulu: If the arrows only appear on hover, then what's the state like when there's no arrows? does the tabs bar still take up the entire width? Do the arrows disappear when someone uses them to move to the top right?

Also, having the arrows only appear on hover might make for some mobile problems, since they wouldn't be usable. We can circumvent this by making the tabs bar scrollable, but then we run into the same problem where the scroll bar is going to take up ~50% of the tabs bar height.

**Comment by jennieab** [comment]
@puddi here's an update from Lin w/ design: 
- When there are no arrows, the tabs bar should take up the entire width. 
- When someone has scrolled all the way to the right, the arrows should disappear until the next time the user hovers. 
- On mobile, the elements should be scrollable. The scroll bar should only appear while the user is scrolling. 

Let me know if you have any remaining outstanding questions! Happy for the 3 of us to chat in person.

**Comment by puddi** [comment]
New version with functionality as described by design engineering: http://welcometotheawakeningzonewevegotufn.weebly.com/

It's kind of like a little bit of ver 1 and ver 2.

**Pull request merged**
